NICE:
  #--------Define the model--------
  num_blocks: 5
  sfactor: 0.3
  hidden_dim: 32
  num_channels: 48 # resolution of the time series 
  condition_dim: 48 # unconditioned generation
  net_type: 'linear'

  #--------Define the training--------
  lr_min: 0.000001
  lr_max: 0.001
  lr_step_size: 100
  w_decay: 0.0
  batch_size: 364

