FCPflow:
  #--------Define the model--------
  num_blocks: 6
  sfactor: 0.7
  hidden_dim: 480
  num_channels: 48 # resolution of the time series 
  condition_dim: 2 # unconditioned generation

  #--------Define the training--------
  lr: 0.0005
  w_decay: 0.0
  batch_size: 2000

