FCPflow:
  #--------Define the model--------
  num_blocks: 3
  sfactor: 0.3
  hidden_dim: 192
  num_channels: 48 # resolution of the time series 
  condition_dim: 2 # unconditioned generation

  #--------Define the training--------
  lr: 0.001
  w_decay: 0.0
  batch_size: 2000

