CWGAN:
  #--------Define the model--------
  input_shape: 24
  cond_dim: 1
  latent_dim: 18
  hidden_dim: 50
  condition_dim: 1

  #--------Define the training--------
  lr_min: 0.000001
  lr_max: 0.001
  lr_step_size: 100
  w_decay: 0.0
  batch_size: 364

