FCPflow:
  #--------Define the model--------
  num_blocks: 4
  sfactor: 0.7
  hidden_dim: 48
  num_channels: 96 # resolution of the time series 
  condition_dim: 1 # unconditioned generation

  #--------Define the training--------
  lr: 0.0001
  w_decay: 0.001
  batch_size: 250

