CWGAN:
  #--------Define the model--------
  input_shape: 48
  cond_dim: 1
  latent_dim: 24
  hidden_dim: 24
  condition_dim: 48

  #--------Define the training--------
  lr_min: 0.000001
  lr_max: 0.001
  lr_step_size: 100
  w_decay: 0.0
  batch_size: 364

